Bump lib9c
planetarium/NineChronicles.Headless pull request #217
Opened 2020-12-16 04:45 UTC by longfin

This PR should be rebased after https://github.com/planetarium/lib9c/pulls merged.

2020-12-16 05:00 UTC, limebell approved these changes

2020-12-16 05:05 UTC, limebell requested changes
Build seems to fail

2021-01-05 06:57 UTC, boscohyun approved these changes

2021-01-05 06:59 UTC, Unengine approved these changes

2021-01-05 07:06 UTC, moreal approved these changes

2021-01-05 07:41 UTC, merged