support-monorocksdb
planetarium/NineChronicles.Headless pull request #354
Opened 2021-03-10 08:14 UTC by area363

This PR takes `monorocksdb` as an option for `--store-type`.
After this PR, `monorocksdb` will take the [original rocksdb(MonoRocksDBStore)](https://github.com/planetarium/libplanet/blob/main/Libplanet.RocksDBStore/MonoRocksDBStore.cs) and `rocksdb` will take the [new rocksdb](https://github.com/planetarium/libplanet/blob/main/Libplanet.RocksDBStore/RocksDBStore.cs).

2021-03-10 08:16 UTC, riemannulus approved these changes

2021-03-11 01:30 UTC, moreal requested changes

2021-03-11 01:30 UTC, moreal commented on Libplanet.Headless/Hosting/LibplanetNodeService.cs
> +                 try
```suggestion
                try
```

2021-03-11 01:32 UTC, moreal requested changes
The build seems failed with the below message.

```
Hosting/LibplanetNodeService.cs(276,46): error CS0234: The type or namespace name 'MonoRocksDBStore' does not exist in the namespace 'Libplanet.RocksDBStore' (are you missing an assembly reference?) [/home/runner/work/NineChronicles.Headless/NineChronicles.Headless/Libplanet.Headless/Libplanet.Headless.csproj]
```

It seems there is no `MonoRocksDB` class at [Libplanet.RocksDB in the submodule](https://github.com/planetarium/libplanet/tree/95a8409bf11017d742be14ff19e49b913ceaeb42/Libplanet.RocksDBStore). Does it need to bump submodule? 🤔

2021-03-11 02:21 UTC, area363 commented
Yes, this will pass after bumping Lib9c to [this branch](https://github.com/planetarium/lib9c/tree/rc-v100036). However, `rc-v100036` hasn't been fixed yet so I'm putting this to hold for now.

2021-03-11 14:43 UTC, longfin commented
I've updated lib9c in NineChronicles.Headless at b7c2cddf.

2021-03-11 14:43 UTC, longfin approved these changes

2021-03-11 14:56 UTC, longfin commented
Oops, I'll bump lib9c once again... 😢

2021-03-11 15:27 UTC, merged